import { NextResponse } from "next/server"

export async function GET() {
const plans = [
    {
      id: "e167c371-e2e1-499e-9de9-99f2d946922f",
      name: "Business Launch",
      code: "business-launch",
      displayOrder: 1,
      eyebrow: "Subscription plan",
      summary: "For growing online shops and commerce teams that need one organized workflow from customer conversation to completed delivery.",
      targetCustomer: "Growing commerce teams that want a structured production rollout.",
      ctaLabel: "Request Business Launch",
      ctaHref: "/contact?intent=sales&source=pricing&planId=e167c371-e2e1-499e-9de9-99f2d946922f",
      recommended: false,
      recommendationLabel: "Recommended plan",
      selfServe: false,
      monthlyPriceDisplay: "500,000 MMK / month",
      periodDurationLabel: "Monthly subscription",
      setupFeeTitle: "Setup and onboarding",
      setupFeeDisplay: "Setup fee applies",
      includedUsersLabel: "Up to 5 team members",
      includedChannelsLabel: "Up to 2 supported channels",
      supportedProvidersLabel: "MESSENGER · TELEGRAM",
      featureList: ["Everything in Business Launch", "Higher workspace usage allowances"],
      availability: "enabled" as const,
      monthlyPrice: 500000,
      maxCsrs: 5,
      maxChannels: 2,
      messageLimit: 20000,
      inboundMessageLimit: 16000,
      outboundMessageLimit: 4000,
      apiLimit: 50000,
      storageLimitGb: 10,
      status: "active",
      public: {
        visible: true,
        displayOrder: 2,
        eyebrow: "Recommended package",
        summary: "For growing online shops and commerce teams.",
        targetCustomer: "Growing commerce teams.",
        recommended: false,
        selfServe: false,
        currencyCode: "MMK",
        billingInterval: "monthly" as const,
        setupFeeMmk: 1000000,
        includedUsersLabel: "Up to 5 team members",
        includedChannelsLabel: "Up to 2 supported channels",
        featureList: ["Everything in Business Launch", "Higher workspace usage allowances"],
        availability: "enabled" as const,
      }
    },
    {
      id: "2ab31ae2-95f9-4883-8ed8-a6d55b9469e8",
      name: "Business Growth",
      code: "business-growth",
      displayOrder: 2,
      eyebrow: "Subscription plan",
      summary: "For established online brands, livestream sellers, and larger teams managing higher conversation and order volumes.",
      targetCustomer: "Larger teams that need broader rollout support and management visibility.",
      ctaLabel: "Request Business Growth",
      ctaHref: "/contact?intent=sales&source=pricing&planId=2ab31ae2-95f9-4883-8ed8-a6d55b9469e8",
      recommended: true,
      recommendationLabel: "Most Popular",
      selfServe: false,
      monthlyPriceDisplay: "1,000,000 MMK / month",
      periodDurationLabel: "Monthly subscription",
      setupFeeTitle: "Implementation",
      setupFeeDisplay: "Setup fee applies",
      includedUsersLabel: "Up to 15 team members",
      includedChannelsLabel: "Up to 4 supported channels",
      supportedProvidersLabel: "MESSENGER · TELEGRAM · VIBER",
      featureList: ["Everything in Business Launch", "Higher workspace usage allowances", "Supervisor and management controls", "Advanced business reports", "Extended data-import assistance"],
      availability: "enabled" as const,
      monthlyPrice: 1000000,
      maxCsrs: 15,
      maxChannels: 4,
      messageLimit: 50000,
      inboundMessageLimit: 40000,
      outboundMessageLimit: 10000,
      apiLimit: 100000,
      storageLimitGb: 25,
      status: "active",
      public: {
        visible: true,
        displayOrder: 3,
        eyebrow: "For larger operations",
        summary: "For established online brands, livestream sellers, and larger teams.",
        targetCustomer: "Larger teams that need broader rollout support.",
        recommended: true,
        selfServe: false,
        currencyCode: "MMK",
        billingInterval: "monthly" as const,
        setupFeeMmk: 2000000,
        includedUsersLabel: "Up to 15 team members",
        includedChannelsLabel: "Up to 4 supported channels",
        featureList: ["Everything in Business Launch", "Higher workspace usage allowances", "Supervisor and management controls", "Advanced business reports"],
        availability: "enabled" as const,
      }
    },
    {
      id: "enterprise-plan-id",
      name: "Enterprise",
      code: "enterprise",
      displayOrder: 3,
      eyebrow: "Subscription plan",
      summary: "Custom commercial scope for larger organizations and tailored workflows.",
      targetCustomer: "Larger organizations with complex needs.",
      ctaLabel: "Contact Sales",
      ctaHref: "/contact?intent=sales&source=pricing&planId=enterprise-plan-id",
      recommended: false,
      recommendationLabel: "Recommended plan",
      selfServe: false,
      monthlyPriceDisplay: "Custom pricing",
      periodDurationLabel: "Monthly subscription",
      setupFeeTitle: "Setup and onboarding",
      setupFeeDisplay: "Custom pricing",
      includedUsersLabel: "Unlimited team members",
      includedChannelsLabel: "Unlimited supported channels",
      supportedProvidersLabel: "All providers",
      featureList: ["All features", "Dedicated support", "Custom integrations"],
      availability: "contact-only" as const,
      monthlyPrice: 0,
      maxCsrs: 50,
      maxChannels: 10,
      messageLimit: 100000,
      inboundMessageLimit: 100000,
      outboundMessageLimit: 100000,
      apiLimit: 200000,
      storageLimitGb: 50,
      status: "active",
      public: {
        visible: true,
        displayOrder: 4,
        eyebrow: "Enterprise",
        summary: "Custom commercial scope for larger organizations.",
        targetCustomer: "Large organizations with complex needs.",
        recommended: false,
        selfServe: false,
        currencyCode: "MMK",
        billingInterval: "monthly" as const,
        setupFeeMmk: 0,
        includedUsersLabel: "Unlimited team members",
        includedChannelsLabel: "Unlimited supported channels",
        featureList: ["All features", "Dedicated support", "Custom integrations"],
        availability: "contact-only" as const,
      }
    }
  ]

  return NextResponse.json(plans)
}
