/**
 * One-off backfill: billing_accounts.icon / qr objectKey -> file.id
 *
 * Historic billing_account rows (K Pay, KBZ) stored the full file-storage
 * objectKey (e.g. "tenants/platform/file-xxx/logo.png") instead of the
 * stable file id (file-xxx). The current frontend resolves images via
 * GET /platform-admin/media/:id/download-url which expects a bare file id;
 * passing an objectKey 404s and slashes break the Next.js proxy path.
 *
 * This script:
 *  - Finds rows where icon or qr contains "/" (objectKey heuristic).
 *  - Resolves each objectKey to the real file.id by:
 *    a) exact objectKey match in file-storage metadata (.data/file-metadata.json)
 *    b) parsing file id from the objectKey (tenants/platform/<fileId>/...)
 *       and verifying that file exists for tenantId=platform
 *    c) listing platform files via FILE_STORAGE_URL (service auth) if metadata
 *       file is not available
 *  - Updates the row to store file.id.
 *  - Logs anything it cannot resolve so an operator can decide to clear or
 *    re-upload.
 *
 * Idempotent and safe to re-run. In non-production dev environments, when a
 * stale objectKey's file record is missing (e.g. .data was wiped), the script
 * will recreate a minimal platform file record with a 1x1 placeholder PNG so
 * that the signed download-url flow works end-to-end (table + form preview).
 * Set CREATE_MISSING_PLACEHOLDER=false to disable that dev helper.
 *
 * Usage:
 *   npm --prefix backend-core-service run backfill:billing-account-media-refs
 *   # or
 *   npx --prefix backend-core-service ts-node src/database/backfill-billing-account-media-refs.ts
 */
import 'reflect-metadata';
import * as fs from 'fs';
import * as path from 'path';
import { config as dotenvConfig } from 'dotenv';
import { AppDataSource } from './data-source';
import { BillingAccount } from '../platform-admin/entities/billing-account.entity';

// Load env so AppDataSource and FILE_STORAGE_URL are available when run via ts-node
dotenvConfig({ path: path.join(__dirname, '../../.env') });
dotenvConfig({ path: path.join(__dirname, '../.env') });

const PLATFORM_SCOPE = 'platform';

// Tiny 1x1 transparent PNG (68 bytes) used as placeholder when the original file content is gone.
const PLACEHOLDER_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=',
  'base64',
);

type FileRecord = {
  id: string;
  tenantId: string;
  fileName: string;
  contentType: string;
  sizeBytes: number;
  purpose?: string;
  objectKey: string;
  storageDriver: string;
  status: string;
  createdAt: string;
  uploadedAt?: string;
  // ownerId exists in file-storage but is optional in some records
  ownerId?: string;
};

function assertNotProduction() {
  const nodeEnv = process.env.NODE_ENV;
  const zayosEnv = process.env.ZAYOS_ENV;
  const allowOverride = process.env.ALLOW_BILLING_MEDIA_BACKFILL === 'true';
  if (
    (nodeEnv === 'production' || zayosEnv === 'production') &&
    !allowOverride
  ) {
    // Backfill mutates billing_accounts and (in dev) may create file-storage records.
    // Require explicit opt-in to run in production.
    throw new Error(
      'Billing media backfill is blocked in production. Set ALLOW_BILLING_MEDIA_BACKFILL=true for an intentional one-off run after rehearsal.',
    );
  }
}

function decodeKey(k: string): string {
  try {
    return decodeURIComponent(k);
  } catch {
    return k;
  }
}

function extractFileId(objectKey: string): string | null {
  const decoded = decodeKey(objectKey);
  const parts = decoded.split('/').filter(Boolean);
  for (const p of parts) {
    // File ids generated by file-storage are file-<timestamp>-<rand>
    if (p.startsWith('file-')) return p;
  }
  return null;
}

function looksLikeObjectKey(value: string | null | undefined): boolean {
  if (!value) return false;
  return value.includes('/') || value.includes('\\');
}

function resolveMetadataPath(): string | null {
  const candidates: Array<string | undefined> = [
    process.env.FILE_METADATA_PATH,
    // When cwd is backend-core-service
    path.resolve(
      __dirname,
      '../../services/file-storage-service/.data/file-metadata.json',
    ),
    // When cwd is repo root
    path.resolve(
      process.cwd(),
      'services/file-storage-service/.data/file-metadata.json',
    ),
    // Legacy relative from backend-core-service/src/database
    path.resolve(
      __dirname,
      '../../../services/file-storage-service/.data/file-metadata.json',
    ),
  ];
  for (const c of candidates) {
    if (!c) continue;
    const p = path.resolve(c);
    if (fs.existsSync(p)) return p;
  }
  // If none exists yet, prefer the canonical location so we can create it
  const canonical = path.resolve(
    __dirname,
    '../../services/file-storage-service/.data/file-metadata.json',
  );
  return canonical;
}

function resolveObjectRoot(): string {
  const fromEnv = process.env.FILE_OBJECT_STORAGE_PATH;
  if (fromEnv) return path.resolve(fromEnv);
  // Derive from metadata path
  const meta = resolveMetadataPath();
  if (meta) return path.resolve(path.dirname(meta), 'files');
  return path.resolve(
    __dirname,
    '../../services/file-storage-service/.data/files',
  );
}

function loadMetadata(metadataPath: string): Record<string, FileRecord> {
  if (!fs.existsSync(metadataPath)) return {};
  try {
    return JSON.parse(fs.readFileSync(metadataPath, 'utf8')) as Record<
      string,
      FileRecord
    >;
  } catch {
    return {};
  }
}

function saveMetadata(metadataPath: string, data: Record<string, FileRecord>) {
  fs.mkdirSync(path.dirname(metadataPath), { recursive: true });
  const tmp = `${metadataPath}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2), 'utf8');
  fs.renameSync(tmp, metadataPath);
}

async function buildObjectKeyMapFromService(): Promise<Map<
  string,
  string
> | null> {
  const serviceUrl = process.env.FILE_STORAGE_URL;
  const signingKey = process.env.INTERNAL_SERVICE_TOKEN_SIGNING_KEY;
  if (!serviceUrl || !signingKey) return null;
  try {
    // Dynamic import to avoid hard dependency when file-storage is not running
    // Package lives at <repoRoot>/packages/internal-service-auth; backend-core-service is one level down.
    const loaded: {
      serviceAuthHeaders: (o: unknown) => Record<string, string>;
      SERVICE_IDENTITIES: Record<string, string>;
      SERVICE_SCOPES: Record<string, string>;
    } =
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      require('../../packages/internal-service-auth/index.js');
    const { serviceAuthHeaders, SERVICE_IDENTITIES, SERVICE_SCOPES } = loaded;
    let page = 1;
    const map = new Map<string, string>();
    // Paginate through platform files
    while (true) {
      const url = `${serviceUrl.replace(/\/$/, '')}/files?page=${page}&limit=100`;
      const res = await fetch(url, {
        headers: {
          'x-tenant-id': PLATFORM_SCOPE,
          ...serviceAuthHeaders({
            audience: SERVICE_IDENTITIES.FILE_STORAGE,
            subject: SERVICE_IDENTITIES.CORE,
            scopes: [SERVICE_SCOPES.FILE_READ],
          }),
        },
      });
      if (!res.ok) break;
      const body = (await res.json()) as {
        data?: FileRecord[];
        hasNext?: boolean;
      };
      for (const f of body.data || []) {
        if (f.objectKey) map.set(f.objectKey, f.id);
        // Also index decoded variant
        if (f.objectKey) map.set(decodeKey(f.objectKey), f.id);
      }
      if (!body.hasNext) break;
      page += 1;
      if (page > 20) break; // safety
    }
    return map;
  } catch {
    return null;
  }
}

async function run() {
  assertNotProduction();
  const createPlaceholder = process.env.CREATE_MISSING_PLACEHOLDER !== 'false';
  const isDev = process.env.NODE_ENV !== 'production';

  await AppDataSource.initialize();
  try {
    const repo = AppDataSource.getRepository(BillingAccount);

    const rows: BillingAccount[] = await repo
      .createQueryBuilder('b')
      .where(
        "b.icon LIKE '%/%' OR b.icon LIKE '%\\\\%' OR b.qr LIKE '%/%' OR b.qr LIKE '%\\\\%'",
      )
      .getMany();

    // Fallback: also check in memory for any that LIKE missed due to encoding
    const all = rows.length ? rows : await repo.find();
    const targetRows = rows.length
      ? rows
      : all.filter(
          (r) => looksLikeObjectKey(r.icon) || looksLikeObjectKey(r.qr),
        );

    if (targetRows.length === 0) {
      console.log(
        'No billing_account rows with objectKey-style icon/qr found. Nothing to do.',
      );
      return;
    }

    console.log(
      `Found ${targetRows.length} billing_account row(s) with legacy objectKey refs.`,
    );

    const metadataPath = resolveMetadataPath();
    const objectRoot = resolveObjectRoot();
    let metadata: Record<string, FileRecord> = {};
    const objectKeyToId = new Map<string, string>();

    if (metadataPath && fs.existsSync(metadataPath)) {
      metadata = loadMetadata(metadataPath);
      for (const rec of Object.values(metadata)) {
        if (rec.tenantId === PLATFORM_SCOPE && rec.objectKey) {
          objectKeyToId.set(rec.objectKey, rec.id);
          objectKeyToId.set(decodeKey(rec.objectKey), rec.id);
        }
      }
      console.log(
        `Loaded ${Object.keys(metadata).length} file record(s) from ${metadataPath} (${objectKeyToId.size} platform objectKeys indexed).`,
      );
    } else {
      console.log(
        `File metadata not found at ${metadataPath}, will try file-storage service API.`,
      );
    }

    // Supplement with live service listing (if available and metadata was sparse)
    if (objectKeyToId.size < 5) {
      const svcMap = await buildObjectKeyMapFromService();
      if (svcMap && svcMap.size) {
        for (const [k, v] of svcMap)
          if (!objectKeyToId.has(k)) objectKeyToId.set(k, v);
        console.log(
          `Supplemented with ${svcMap.size} platform files from file-storage service API.`,
        );
      }
    }

    let updatedRows = 0;
    let updatedFields = 0;
    const unresolved: Array<{
      accountId: string;
      accountName: string;
      field: 'icon' | 'qr';
      value: string;
      reason: string;
    }> = [];
    let metadataDirty = false;

    for (const row of targetRows) {
      let rowDirty = false;
      for (const field of ['icon', 'qr'] as const) {
        const raw = (row as unknown as Record<string, string | null>)[field];
        if (!looksLikeObjectKey(raw)) continue;
        const objectKey = raw as string;
        let fileId: string | null = null;

        // 1) Exact objectKey match in metadata / service map
        if (objectKeyToId.has(objectKey)) {
          fileId = objectKeyToId.get(objectKey) || null;
        } else if (objectKeyToId.has(decodeKey(objectKey))) {
          fileId = objectKeyToId.get(decodeKey(objectKey)) || null;
        }

        // 2) Parse file id from objectKey and verify it exists (tenantId=platform)
        if (!fileId) {
          const parsed = extractFileId(objectKey);
          if (parsed) {
            const rec = metadata[parsed];
            if (rec && rec.tenantId === PLATFORM_SCOPE) {
              fileId = parsed;
            } else if (metadata[parsed]) {
              // File exists but under different tenant — treat as not correctly resolved for platform scope
              unresolved.push({
                accountId: row.id,
                accountName: row.accountName,
                field,
                value: objectKey,
                reason: `parsed fileId ${parsed} exists but tenantId=${metadata[parsed].tenantId} != platform`,
              });
              continue;
            } else {
              // No record yet — in dev we can recreate a placeholder so the download-url flow works
              if (isDev && createPlaceholder) {
                const rawFileName =
                  decodeKey(objectKey).split('/').pop() || `${field}.png`;
                // Mirror LocalDiskStorageAdapter.safeFileName: keep word chars, dot, hyphen
                const safeName =
                  rawFileName
                    .replace(/[^\w.-]+/g, '-')
                    .replace(/^-+|-+$/g, '') || 'file.png';
                const objectKeyForRecord = `tenants/${PLATFORM_SCOPE}/${parsed}/${encodeURIComponent(safeName)}`;
                // Prefer the original objectKey if it already looks like a valid tenants/platform key
                const finalObjectKey = objectKey.startsWith('tenants/')
                  ? objectKey
                  : objectKeyForRecord;
                const now = new Date().toISOString();

                const rec2: FileRecord & { ownerId?: string } = {
                  id: parsed,
                  tenantId: PLATFORM_SCOPE,
                  ownerId: 'platform-backfill',
                  fileName: safeName,
                  contentType: 'image/png',
                  sizeBytes: PLACEHOLDER_PNG.length,
                  purpose: 'platform-billing-account',
                  objectKey: finalObjectKey,
                  storageDriver: 'local-disk',
                  status: 'registered',
                  createdAt: now,
                  uploadedAt: now,
                };
                metadata[parsed] = rec2;
                objectKeyToId.set(finalObjectKey, parsed);
                objectKeyToId.set(decodeKey(finalObjectKey), parsed);
                metadataDirty = true;
                // Ensure file content exists on disk for LocalDiskStorageAdapter.readObject
                try {
                  const objectPath = path.resolve(objectRoot, finalObjectKey);
                  if (
                    !objectPath.startsWith(path.resolve(objectRoot) + path.sep)
                  ) {
                    throw new Error(
                      `Refusing to write outside objectRoot: ${objectPath}`,
                    );
                  }
                  fs.mkdirSync(path.dirname(objectPath), { recursive: true });
                  if (!fs.existsSync(objectPath)) {
                    fs.writeFileSync(objectPath, PLACEHOLDER_PNG);
                    console.log(
                      `Created placeholder file content for ${parsed} at ${objectPath} (from ${field} ${objectKey})`,
                    );
                  }
                } catch (e) {
                  console.warn(
                    `Failed to create placeholder content for ${parsed}:`,
                    e,
                  );
                }
                fileId = parsed;
                console.log(
                  `Recreated missing platform file record ${parsed} for ${row.accountName}.${field} (objectKey ${objectKey}) as placeholder.`,
                );
              } else {
                unresolved.push({
                  accountId: row.id,
                  accountName: row.accountName,
                  field,
                  value: objectKey,
                  reason: `parsed fileId ${parsed} not found in file-storage metadata; re-upload required`,
                });
                continue;
              }
            }
          }
        }

        if (!fileId) {
          unresolved.push({
            accountId: row.id,
            accountName: row.accountName,
            field,
            value: objectKey,
            reason:
              'no matching file record and could not parse fileId from objectKey',
          });
          continue;
        }

        (row as unknown as Record<string, string | null>)[field] = fileId;
        rowDirty = true;
        updatedFields += 1;
        console.log(
          `Resolved ${row.accountName} (${row.id}) ${field}: "${objectKey}" -> "${fileId}"`,
        );
      }

      if (rowDirty) {
        await repo.save(row);
        updatedRows += 1;
      }
    }

    if (metadataDirty && metadataPath) {
      saveMetadata(metadataPath, metadata);
      console.log(`Wrote updated file metadata to ${metadataPath}`);
    }

    console.log(`\n=== Backfill summary ===`);
    console.log(`Scanned: ${targetRows.length} row(s)`);
    console.log(`Updated rows: ${updatedRows}`);
    console.log(`Updated fields: ${updatedFields}`);
    if (unresolved.length) {
      console.warn(
        `Unresolved: ${unresolved.length} field(s) could not be mapped. Manual action required (clear or re-upload):`,
      );
      for (const u of unresolved) {
        console.warn(
          ` - ${u.accountName} ${u.accountId} ${u.field}="${u.value}" :: ${u.reason}`,
        );
      }
      console.warn(
        'Frontend will show the \"no image\" placeholder for these fields (no spinner) thanks to the defensive guard in page.tsx.',
      );
    } else {
      console.log('All legacy refs resolved.');
    }
  } finally {
    await AppDataSource.destroy();
  }
}

run().catch((err) => {
  console.error('Billing media backfill failed:', err);
  process.exit(1);
});
